// Imported from sources/GNP-rules-v6.csv. Preserve all source fields.
export const ACTIONS_ESCALATIONS_V6_ROWS = [
  [
    "Litter",
    "Low",
    "LITTER-1",
    "1",
    "1-2",
    "24 hours",
    "",
    "",
    "Action",
    "False",
    "Site-owned issue",
    "Clean up the litter.",
    "Pick up the litter",
    "File 311 ticket on action creation",
    "1.1.4.7.20.0",
    "76",
    "48",
    "If there is a small amount of trash, pick it up yourself during your regular checks.",
    "There's too much trash for me to collect\nNot within the immediate area",
    "Policy lines 68-69",
  ],
  [
    "Litter",
    "Low",
    "LITTER-2",
    "1",
    "3-5",
    "24 hours",
    "",
    "",
    "Escalation",
    "True",
    "Department of Public Works (DPW)",
    "Ask the City to clean the street.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "1.1.4.7.20.0",
    "'-'",
    "48",
    "If there is too much trash for you to clean up, you can use the app to file a 311 ticket and ask the City for help.",
    "We already filed a ticket",
    "Public 311 info",
  ],
  [
    "Bulky items",
    "Low",
    "BULKY-1",
    "1",
    "1-5",
    "24 hours",
    "Are these items from your site?",
    "provider_generated == true",
    "Action",
    "True",
    "Recology",
    "Call for pickup.",
    "Call for pickup",
    "File 311 ticket on action creation",
    "1.19.1.22.0.0",
    "76",
    "4",
    "If the item is yours (like old furniture from your program), call Recology (or a private hauler) to set up a pickup.",
    "It doesn't feel safe",
    "Policy line 69; Recology public info",
  ],
  [
    "Bulky items",
    "Low",
    "BULKY-2",
    "1",
    "1-5",
    "24 hours",
    "Are these items from your site?",
    "provider_generated == false",
    "Escalation",
    "True",
    "Department of Public Works (DPW)",
    "Report it. Do not move it yourself.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "Run bulky item analysis",
    "'-'",
    "4",
    "If the item isn't yours, report it to the City. You don't have to move it.",
    "We already filed a ticket",
    "GNP-2 original; public SF311 taxonomy",
  ],
  [
    "Feces and urine",
    "High",
    "FECES-1",
    "1",
    "1-4",
    "24 hours",
    "Is from an animal owned by a resident or client on site?",
    "provider_generated == true",
    "Action",
    "True",
    "Site-owned issue",
    "Ask the animal's owner to clean this up.",
    "Ask the owner to clean it up",
    "File 311 ticket on action creation",
    "1.19.1.22.0.0",
    "'-'",
    "4",
    "When the waste is from an animal owned by a client or resident, ask them to clean it up.",
    "We already filed a ticket",
    "Policy line 70; public SF311 taxonomy",
  ],
  [
    "Feces and urine",
    "High",
    "FECES-2",
    "1",
    "1-4",
    "24 hours",
    "Is from an animal owned by a resident or client on site?",
    "provider_generated == false",
    "Escalation",
    "True",
    "Department of Public Works (DPW)",
    "Do not touch it. Report it to the City.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "1.1.4.7.9.0",
    "'-'",
    "24",
    "Stay away from it. Use the app to file a 311 ticket so the City can clean it up.",
    "'-'",
    "Policy line 70; public SF311 taxonomy",
  ],
  [
    "Feces and urine",
    "High",
    "FECES-3",
    "1",
    "5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Police Department (SFPD)",
    "Call the SFPD non-emergency line.",
    "Call SFPD: 415-553-0123",
    "File 311 ticket on escalation creation",
    "1.19.1.20.0.0",
    "76",
    "12",
    "Call the SFPD non-emergency line: 415-553-0123.",
    "We already called",
    "Policy line 70; public SF311 taxonomy",
  ],
  [
    "Needles",
    "High",
    "NEEDLES-1",
    "1",
    "1-5",
    "17:01-08:59",
    "",
    "",
    "Escalation",
    "True",
    "Department of Public Works (DPW)",
    "Do not touch the needle. Report it to the City.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "1.1.4.7.12.0",
    "'-'",
    "24",
    "Never pick up a needle yourself. Use the app to file a 311 ticket so the City can safely remove it.",
    "We already filed a ticket",
    "Policy line 70",
  ],
  [
    "Needles",
    "High",
    "NEEDLES-2",
    "1",
    "1-5",
    "09:00-17:00",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF AIDS Foundation (SFAF)",
    "Do not touch the needle. Call it in to SFAF.",
    "Call SFAF: 415-818-7769",
    "File 311 ticket on escalation creation",
    "1.1.4.7.12.0",
    "76",
    "24",
    "Never pick up a needle yourself. SFAF will come pick it up safely. Call 415-818-7769.",
    "We already filed a ticket",
    "Policy line 70",
  ],
  [
    "Tents, tarps, or bedding",
    "High",
    "TENTS-1",
    "1",
    "1-5",
    "24 hours",
    "",
    "",
    "Escalation",
    "True",
    "DPH Street Team via 311",
    "Don't remove. Report to the City.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "1.23.1.1.1.0",
    "'-'",
    "96",
    "Encampment resolution is the City's responsibility. Use the app to file a 311 ticket.",
    "We already filed a ticket",
    "Policy lines 104-108",
  ],
  [
    "Graffiti",
    "Low",
    "GRAFFITI-1",
    "1",
    "1-3",
    "24 hours",
    "Is this on site property?",
    "location == provider_controlled_property",
    "Action",
    "True",
    "Site-owned issue",
    "Clean off the graffiti.",
    "Clean up the graffiti",
    "File 311 ticket on action creation",
    "Run graffiti analysis",
    "76",
    "72",
    "If the graffiti is on your own building, remove it yourself within 3 days.",
    "It doesn't feel safe\nIt's too much for us to clean",
    "Policy line 115",
  ],
  [
    "Graffiti",
    "Low",
    "GRAFFITI-2",
    "1",
    "1-3",
    "24 hours",
    "Is this on site property?",
    "location != provider_controlled_property",
    "Escalation",
    "True",
    "Department of Public Works (DPW)",
    "Ask the City to clean the graffiti.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "Run graffiti analysis",
    "'-'",
    "72",
    "If the graffiti is not on your property, report it to the City instead of cleaning it yourself.",
    "We already filed a ticket",
    "Policy line 116; public DPW info",
  ],
  [
    "Graffiti",
    "Low",
    "GRAFFITI-3",
    "1",
    "4",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Police Department (SFPD)",
    "Call the SFPD non-emergency line.",
    "Call SFPD: 415-553-0123",
    "File 311 ticket on escalation creation",
    "1.19.1.20.0.0",
    "76",
    "12",
    "When someone is actively spraying graffiti, call the SFPD non-emergency line.",
    "We already called",
    "Policy line 116; public DPW info",
  ],
  [
    "Graffiti",
    "Low",
    "GRAFFITI-4",
    "1",
    "5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Police Department (SFPD)",
    "Call 911 right away.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.20.0.0",
    "76",
    "12",
    "Potential hate speech, especially on the side of a place of worship, must be investigated by the SFPD. Call 911.",
    "We already called 911",
    "Policy line 116; public DPW info",
  ],
  [
    "Fire hazard",
    "High",
    "FIRE-1",
    "1",
    "1-2",
    "08:00-17:00, Mo+Tu+We+Th+Fr",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Fire Department (SFFD)\t",
    "Call SFFD during business hours.",
    "Call SFFD: 415-558-3300",
    "File 311 ticket on escalation creation",
    "1.1.4.7.15.0",
    "76",
    "12",
    "If it looks unsafe but nothing is on fire, Monday to Friday, 8 am to 5 pm, call SFFD on 415-558-3300.",
    "We already filed a ticket",
    "Public SFFD info",
  ],
  [
    "Fire hazard",
    "High",
    "FIRE-2",
    "1",
    "1-2",
    "08:00-17:00, Sa+Su",
    "",
    "",
    "Escalation",
    "True",
    "311 (will be routed)",
    "Report it to the City.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "1.17.1.32.1.7",
    "'-'",
    "12",
    "If it looks unsafe but nothing is on fire, and it's on the weekend, use the app to file a 311 ticket.",
    "We already filed a ticket",
    "Public SFFD info",
  ],
  [
    "Fire hazard",
    "High",
    "FIRE-3",
    "1",
    "1-2",
    "17:01-07:59",
    "",
    "",
    "Escalation",
    "True",
    "311 (will be routed)",
    "Report it to the City.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "1.17.1.32.1.7",
    "'-'",
    "12",
    "If it looks unsafe but nothing is on fire, and it's after business hours, use the app to file a 311 ticket.",
    "We already filed a ticket",
    "Public SFFD info",
  ],
  [
    "Fire hazard",
    "High",
    "FIRE-4",
    "1",
    "3-5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Fire Department (SFFD)",
    "Call 911 right away.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.20.0.0",
    "76",
    "0",
    "If you see fire, smoke, or something about to catch fire, call 911 now.",
    "We already called 911",
    "Policy Appendix A",
  ],
  [
    "Blocked doorway or sidewalk",
    "Moderate",
    "BLOCK-1",
    "1",
    "1-2",
    "24 hours",
    "Is this blockage due to your clients or residents?",
    "affiliated == true",
    "Action",
    "True",
    "Site-owned issue",
    "Ask them to move.",
    "Ask them to move",
    "File 311 ticket on action creation",
    "1.19.1.22.0.0",
    "76",
    "4",
    "If it's your client or guest, and it's safe, just ask them to move.",
    "It doesn't feel safe\nWe already spoke to them",
    "Policy lines 92, 31",
  ],
  [
    "Blocked doorway or sidewalk",
    "Moderate",
    "BLOCK-2",
    "1",
    "1-2",
    "24 hours",
    "Is this blockage due to your clients or residents?",
    "affiliated == false",
    "Escalation",
    "True",
    "311 (will be routed)",
    "Report it to the City.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "Run bulky item analysis",
    "'-'",
    "4",
    "If it's an object (not a person) blocking the path, use the app to file a 311 ticket.",
    "'-'",
    "Public SF311 taxonomy",
  ],
  [
    "Blocked doorway or sidewalk",
    "Moderate",
    "BLOCK-3",
    "1",
    "3-5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Fire Department (SFFD)",
    "Call the SFPD non-emergency line.",
    "Call SFPD: 415-553-0123",
    "File 311 ticket on escalation creation",
    "1.19.1.20.0.0",
    "76",
    "4",
    "If the path is badly blocked, or they won't move, call the SFPD non-emergency line: 415-553-0123.",
    "'-'",
    "Policy Appendix A",
  ],
  [
    "Public drug use",
    "Moderate",
    "DRUG-1",
    "1",
    "1",
    "24 hours",
    "Are they a site client or resident?",
    "affiliated == true",
    "Action",
    "True",
    "Site-owned issue",
    "Offer help, if it's safe.",
    "Offer help",
    "File 311 ticket on action creation",
    "1.19.1.22.0.0",
    "76",
    "4",
    "If it's your client and it's safe, talk to them calmly. Offer to connect them with help.",
    "It doesn't feel safe\nWe already spoke to them",
    "Policy lines 93-95, 34",
  ],
  [
    "Public drug use",
    "Moderate",
    "DRUG-2",
    "1",
    "1",
    "24 hours",
    "Are they a site client or resident?",
    "affiliated == false",
    "Non-Actionable Escalation",
    "True",
    "SF Police Department (SFPD)",
    "Call the SFPD non-emergency line.",
    "Call SFPD: 415-553-0123",
    "File 311 ticket on escalation creation",
    "1.19.1.20.0.0",
    "76",
    "4",
    "If it's not your client, report it to the City. Don't step in.",
    "We already called 911",
    "Policy line 29, 35",
  ],
  [
    "Public drug use",
    "Moderate",
    "DRUG-3",
    "1",
    "2-4",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Police Department (SFPD)",
    "Call the SFPD non-emergency line.",
    "Call SFPD: 415-553-0123",
    "File 311 ticket on escalation creation",
    "1.19.1.20.0.0",
    "76",
    "4",
    "Call the SFPD non-emergency line: 415-553-0123",
    "",
    "",
  ],
  [
    "Public drug use",
    "Moderate",
    "DRUG-4",
    "1",
    "5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Police Department (SFPD)",
    "Call 911 right away.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "0",
    "If someone looks like they may be overdosing or in serious trouble, call 911 now.",
    "We already called 911",
    "Policy Appendix A",
  ],
  [
    "Someone in distress",
    "High",
    "DISTRESS-1",
    "1",
    "4-5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "911 (will be routed)",
    "Call 911 right away.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "0",
    "If someone is in real danger right now, call 911. The City will send the right team to help.",
    "We already called 911",
    "Policy Appendix A; public SF Coordinated Street Response info",
  ],
  [
    "Someone in distress",
    "High",
    "DISTRESS-2",
    "1",
    "1-3",
    "24 hours",
    "Are they a site client or resident?",
    "affiliated == true",
    "Action",
    "False",
    "Site-owned issue",
    "Offer help, if it's safe.",
    "Offer help",
    "File 311 ticket on action creation",
    "1.19.1.22.0.0",
    "76",
    "1",
    "If it's your client, it's not an emergency, and it's safe, talk to them gently and offer to connect them with help.",
    "'-'",
    "Policy lines 94-95, 34",
  ],
  [
    "Someone in distress",
    "High",
    "DISTRESS-3",
    "1",
    "1-3",
    "24 hours",
    "Are they a site client or resident?",
    "affiliated == false",
    "Non-Actionable Escalation",
    "True",
    "911 (will be routed)",
    "Report it. Do not try to handle it yourself.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "0",
    "If it's not your client, or it doesn't feel safe, call 911.",
    "We already called 911",
    "Policy line 29",
  ],
  [
    "Animals",
    "Moderate",
    "ANIMAL-1",
    "1",
    "1-2",
    "24 hours",
    "Is this animal owned by a site client or resident?",
    "affiliated == true",
    "Action",
    "True",
    "Site-owned issue",
    "Speak to them about their animal.",
    "Speak to them about their animal",
    "File 311 ticket on action creation",
    "1.19.1.22.0.0",
    "76",
    "1",
    "If the animal belongs to one of your clients, remind them to leash it and pick up its waste.",
    "It doesn't feel safe\nWe already reminded them",
    "Policy lines 119-124",
  ],
  [
    "Animals",
    "Moderate",
    "ANIMAL-2",
    "1",
    "1-2",
    "06:00-23:59",
    "Is this animal owned by a site client or resident?",
    "affiliated == false",
    "Non-Actionable Escalation",
    "True",
    "SF Animal Care & Control (SFACC)",
    "Call SF Animal Care and Control.",
    "Call SFACC: 415-554-9400",
    "File 311 ticket on escalation creation",
    "1.19.1.22.0.0",
    "76",
    "12",
    "If it's a stray or unknown animal, call Animal Care and Control on 415-554-9400",
    "We already called SFACC\nWe already filed a ticket",
    "Public SFACC info",
  ],
  [
    "Animals",
    "Moderate",
    "ANIMAL-3",
    "1",
    "1-2",
    "00:00-05:59",
    "Is this animal owned by a site client or resident?",
    "affiliated == false",
    "Escalation",
    "True",
    "311 (will be routed)",
    "Report it to the City.",
    "File 311 ticket",
    "Create and file 311 ticket on confirmation",
    "1.19.1.22.0.0",
    "'-'",
    "6",
    "It's outside of Animal Care and Control opening hours. File a ticket with the City and 311 will route it appropriately.",
    "We already filed a ticket",
    "Public SFACC info",
  ],
  [
    "Animals",
    "High",
    "ANIMAL-4",
    "1",
    "3-5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "911 (will be routed)",
    "Call 911 right away.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "0",
    "If an animal is attacking someone, call 911 now.",
    "We already called 911",
    "GNP-3",
  ],
  [
    "Medical emergency",
    "High",
    "MED-1",
    "1",
    "1-3",
    "24 hours",
    "Are they asking for medical help?",
    "medical_help == true",
    "Non-Actionable Escalation",
    "True",
    "911 (will be routed)",
    "Call 911 right away.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "0",
    "If they tell you they need medical help, call 911 immediately.",
    "It doesn't feel safe\nWe already checked in with them",
    "GNP-3",
  ],
  [
    "Medical emergency",
    "High",
    "MED-2",
    "1",
    "1-3",
    "24 hours",
    "Are they asking for medical help?",
    "medical_help == false",
    "Action",
    "False",
    "Site-owned issue",
    "Offer help, if it's safe.",
    "Offer help",
    "File 311 ticket on action creation",
    "1.19.1.22.0.0",
    "76",
    "1",
    "If someone just looks tired or a little unwell, check in and offer help. Keep an eye on them in case it gets worse.",
    "It doesn't feel safe\nWe already checked in with them",
    "GNP-3",
  ],
  [
    "Medical emergency",
    "High",
    "MED-3",
    "1",
    "2-5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "911 (will be routed)",
    "Call 911 right away.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "0",
    "If someone is hurt, in pain, or not waking up, call 911 now. Don't wait, even if other people are already helping.",
    "We already called 911",
    "Policy Appendix A",
  ],
  [
    "Threats, intimidation, or violence",
    "Moderate",
    "THREAT-1",
    "1",
    "1-2",
    "24 hours",
    "Are they likely to leave if asked?",
    "refusal_leave == true",
    "Non-Actionable Escalation",
    "True",
    "SF Police Department (SFPD)",
    "Call the SFPD non-emergency line.",
    "Call SFPD: 415-553-0123",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "4",
    "If it turns violent or a weapon is involved, do not get involved. Move to safety and call 911.",
    "We already called 911",
    "Policy line 28; Appendix A",
  ],
  [
    "Threats, intimidation, or violence",
    "Moderate",
    "THREAT-2",
    "1",
    "1-2",
    "24 hours",
    "Are they likely to leave if asked?",
    "refusal_leave == false",
    "Action",
    "True",
    "Site-owned issue",
    "Ask them to leave.",
    "Ask them to leave",
    "File 311 ticket on action creation",
    "1.19.1.22.0.0",
    "76",
    "4",
    "If it turns violent or a weapon is involved, do not get involved. Move to safety and call 911.",
    "We already called 911",
    "Policy line 28; Appendix A",
  ],
  [
    "Threats, intimidation, or violence",
    "High",
    "THREAT-3",
    "1",
    "3-5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "911 (will be routed)",
    "Call 911 right away.",
    "Call 911",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "0",
    "If it turns violent or a weapon is involved, do not get involved. Move to safety and call 911.",
    "We already called 911",
    "Policy line 28; Appendix A",
  ],
  [
    "Illegal parking",
    "Low",
    "PARKING-1",
    "1",
    "1-5",
    "24 hours",
    "",
    "",
    "Non-Actionable Escalation",
    "True",
    "SF Municipal Transportation Agency (SFMTA)",
    "Call 311.",
    "Call 311",
    "File 311 ticket on escalation creation",
    "1.19.1.21.0.0",
    "76",
    "4",
    "Illegal parking issues are reported via 311, but we can't file this automatically for you. Call 311 to explain the problem.  ",
    "'-'",
    "",
  ],
];
